### ISSUE TITLE
Touch detection

### ISSUE THREAD

**Issue by alexsomeoddpilot** [SomeoddpilotInc/sop-styl#4]
@krispy1298 or @megrymo, can you fill in here about what this should be doing?

**Comment by krispy1298** [comment]
## JS
* Detect if device is touch enabled
* If so, add a class to the body(?)

## Stylus
* classes for touch-hide, touch-show (similar to responsive hide)

@megrymo anything else?

**Comment by alexsomeoddpilot** [comment]
This sounds like it belongs in the UI project. sop-styl should only be for Stylus helpers.
